[build]
  publish = "dist"
  command = "npm run build"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Preload critical resources
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = '''
    </assets/index.css>; rel=preload; as=style,
    </assets/index.js>; rel=preload; as=script
    '''

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# API redirects (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://api.innovatesphere.com/:splat"
  status = 200
  force = true